### ISSUE TITLE
inject service stubs with beforeEach

### ISSUE THREAD

**Issue by Ramblurr** [elwayman02/ember-sinon-qunit#117]
In vanilla ember + qunit once can do:

```js
moduleForComponent('my-component', 'Integration | Component | my component', {
  integration: true,
  beforeEach() {
    this.register('service:thing', thingService);
    this.inject.service('thing', { as: 'thingService' });
  }
});


test('it renders', function(assert) {
// this.subject has thingService injected into it
});
```

How can we achieve this with ember-sinon-qunit where thingService is a spy/stub?

**Comment by elwayman02** [comment]
I'm not clear on how/why you would have a service *object* be a spy/stub *function*, but if you meant to stub a specific method on the service, you can do so after injecting it I believe.

Right now the sandbox only exists around the `test` method, but there are three approaches you can use:

1) Import sinon directly for the stub and manually handle cleanup
2) Create the spy/stub in every test
3) Use a "setup method" that gets called at the beginning of each test (my preference)

```
let fooStub;
function setup(thingService) {
  fooStub = this.stub(thingService, 'foo');
}

test('foo stubs', function (assert) {
  setup.call(this, thingService);
  // ...do the thing
  assert.ok(fooStub.calledOnce);
});
```
