### ISSUE TITLE
sinon.match support

### ISSUE THREAD

**Issue by Bockit** [elwayman02/ember-sinon-qunit#12]
Hi,

Love the package! Was just wondering if there's a reason [sinon.match][match] isn't being [added as a property][properties]? Happy to make a PR if it's just oversight.

Thanks for your time.

[match]: http://sinonjs.org/docs#matchers
[properties]: https://github.com/elwayman02/ember-sinon-qunit/blob/master/test-support/ember-sinon-qunit/test.js#L17

**Comment by elwayman02** [comment]
@Bockit yea, there's no specific reason for that, probably an oversight. I think I was just using the example from [sinon-qunit](https://github.com/cjohansen/sinon-qunit/blob/master/lib/sinon-qunit.js) when setting up the config. I would more than welcome a PR for this!

**Comment by elwayman02** [comment]
@Bockit upon further investigation, I'm not sure if the [Sandbox API](http://sinonjs.org/docs/#sandbox) supports `match`. Can you please try adding this property and add a test that makes sure it's working? If so, I'm happy to merge that PR.

**Comment by sukima** [comment]
You can still `import sinon from 'sinon'` and have `sinon.match.any()` work just fine. Great for `sinon.assert.called()` APIs because the sinon qunit uses assert under the hood and provides a message.

```javascript
// => expected spy to be called with arguments typeOf("string")
sinon.assert.calledWith(this.spy(), sinon.match.string);
// VS.
assert.ok(this.spy().calledWith(sinon.match.string), 'expected the spy to have been called with a string.'); 
```

**Comment by elwayman02** [comment]
:+1: perhaps that's the best solution unless you want to submit a PR to Sinon to add `match` to sandboxes @Bockit. Closing for now, feel free to re-open if you come up with new ideas on how to implement this.

**Comment by sukima** [comment]
I just looked into [the source](https://github.com/sinonjs/sinon/blob/ac12b30f58db1f9014ae7c6f6ca235dcdabaf732/lib/sinon/assert.js#L135-L167) and it seems the `sinon.assert.expose()` method will graph the assert API onto `this` and also the match API. Two birds with one stone!

**Comment by elwayman02** [comment]
That's awesome! Do you want to attempt a PR?

**Comment by sukima** [comment]
@elwayman02 Tried, didn't work as expected, It added the assert API but not the matchers:

```javascript
this.assertCalledWith(mySpy, sinon.match(myExpectedObj)); // Worked
this.assertCalledWith(mySpy, this.assertMatch(myExpectedObj)); // Did not work
```

It may still be worth exposing the assert API. But it seems one still needs the sinon global for using matchers.
