### ISSUE TITLE
TypeError: log.gauge.isEnabled is not a function

### ISSUE THREAD

**Issue by CezaryH** [elwayman02/ember-sinon-qunit#120]
TypeError: log.gauge.isEnabled is not a function on ember install ember-sinon-qunit with ember-cli: 2.11.1

**Comment by elwayman02** [comment]
Can you provide more information on this? There is nothing in this addon that uses a `log.gauge` or anything similar.

**Comment by meetbryce** [comment]
Try downgrading your node version to the lts release
