### ISSUE TITLE
Add support for `only`

### ISSUE THREAD

**Issue by GCheung55** [elwayman02/ember-sinon-qunit#136]
Qunit provides an `only` function to run a single test. This would be really helpful.

**Comment by elwayman02** [comment]
I think this is a great idea! I'm not sure exactly when I'll have time to add this, but would welcome PRs if anyone wanted to take a shot.

**Comment by snewcomer** [comment]
@elwayman02 Would this involve essentially the same semantics as `test` to create a sandboxed environment?

**Comment by elwayman02** [comment]
Seems likely @snewcomer

**Comment by elwayman02** [comment]
@GCheung55 please test the new release and let us know if you find any issues!
