### ISSUE TITLE
this.stub and usingPromise

### ISSUE THREAD

**Issue by vitch** [elwayman02/ember-sinon-qunit#145]
Sinon [lets you specify](http://sinonjs.org/releases/v4.1.2/stubs/#stubusingpromisepromiselibrary) the promise library used by `stub.resolves`. It would be nice if this wrapper could automatically set it to `RSVP`. I had a quick look through the code but I wasn't sure where to add something like this...

**Comment by elwayman02** [comment]
Hmm, this looks like a function of the stub method itself, which makes it too far downstream. If there's a way to configure the entire sinon sandbox to default to a particular promise library, we should absolutely do that.

**Comment by elwayman02** [comment]
Looks like there is `sandbox.usingPromise(promiseLibrary);`, which means we can probably use this to do what you need! Nice callout.
