### ISSUE TITLE
wrench.js is deprecated!

### ISSUE THREAD

**Issue by izelnakri** [elwayman02/ember-sinon-qunit#148]
ember-sinon-qunit > ember-sinon > sinon > build > wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

**Comment by elwayman02** [comment]
This seems like a ticket you should file with `sinon` or `build`. We don't control those upstream dependencies.
