### ISSUE TITLE
fakeTimers // lodex access

### ISSUE THREAD

**Issue by erichonkanen** [elwayman02/ember-sinon-qunit#149]
Hey I notice that this lib isn't exposing the lodex module from sinon so e.g. I can't do `this.useFakeTimers()` or `this.clock.<tick|etc>`

Would it make sense to expose this as it's part of sinon? (despite also being an external module)

http://sinonjs.org/releases/v4.4.2/fake-timers/

**Comment by elwayman02** [comment]
That seems reasonable! If you feel up to taking a pass at a PR, I'd be happy to review it.

**Comment by elwayman02** [comment]
Closing as the recent changes now allow you to use the sinon import directly again!
