### ISSUE TITLE
Merge w/ ember-sinon-sandbox

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-sinon-qunit#155]
https://github.com/scalvert/ember-sinon-sandbox

This addon has great awareness of the latest Ember testing patterns, and ember-sinon-qunit can benefit from adopting some of these approaches.

We should probably detail a few things to understand better how to merge:

- [ ] What features are unique in these addons?
- [ ] What features are the same, but implemented differently (or different DSL)?

Ping @scalvert for thoughts here. :)

**Comment by scalvert** [comment]
I definitely like the idea of merging two overlapping repos into one. I'll spend a bit of time going through each to see the potential intersection points. 

Thanks for reaching out!

**Comment by elwayman02** [comment]
@scalvert have you had any thoughts on how we can best proceed adding the best of both packages into one repo?

**Comment by gustaff-weldon** [comment]
@scalvert @elwayman02 any progress on that? We are currently using `ember-sinon-qunit` and switch recently to Ember 3.5 but with the new cleaner qunit separation.  We would welcome a change from:
```
import test from 'ember-sinon-qunit/test-support/test';
import { setupTest } from 'ember-qunit';

module('Unit | Route | foo', function(hooks) {
  setupTest(hooks);
```

to:
```
import { setupSinonTest } from 'ember-sinon-qunit/test-support/test';
import { setupTest } from 'ember-qunit';

module('Unit | Route | foo', function(hooks) {
  setupTest(hooks);
  setupSinonTest(hooks);
```
without sacrificing support and features if possible.

**Comment by elwayman02** [comment]
This is a great idea that we should definitely look into supporting. I don't know when I'll have time personally to tackle this, but I would support a PR if someone wants to take it on.

**Comment by scalvert** [comment]
The reason I continue to use ember-sinon-sandbox, which I'm planning on updating soon with a slightly simpler approach, is because it's hands off. You don't need to explicitly call a hooks style API (which I like, btw) in order to ensure your sinon mocks/stubs/spies are restored. I'd rather keep the restoration of those separate from userland per se. 

Thoughts?

**Comment by elwayman02** [comment]
@scalvert can you clarify what you mean by that? Pretty much the only reason `ember-sinon-qunit` exists is to make sure users *don't* have to manually restore their mocks/stubs/spies...the entire sandbox is cleaned up automatically. So I must be misunderstanding what you're referring to here...

**Comment by scalvert** [comment]
I’m referring to having a hooks call that presumably sets up the afterEach that restores the sandbox. I like the approach of not requiring the user to do this for every test module.

**Comment by elwayman02** [comment]
`ember-sinon-qunit` doesn't have anything like that. It's automated.

**Comment by scalvert** [comment]
I believe if you look above, @gustaff-weldon was suggesting a potential hooks API that is provided that would do the auto restoration. This is what I was referring to.

**Comment by elwayman02** [comment]
Ah, ok, thanks for explaining!

**Comment by elwayman02** [comment]
Isn't that the exact API that ember-sinon-sandbox is supporting right now, though?

**Comment by scalvert** [comment]
You're not wrong, but after 2 years of my using `ember-sinon-sandbox` it's become clear to me that providing a hook like that that's dependent on the engineer remembering to use it _otherwise_ you can get `sinon` state leakage between tests is brittle.

I'd much prefer to provide a one-time setup call like [ember-lifeline](https://github.com/ember-lifeline/ember-lifeline/blob/master/addon-test-support/index.js#L8) does for its validation is preferable.

I plan to deprecate the hooks API in favor of this one-time setup API.

**Comment by elwayman02** [comment]
So then maybe we should propose a single API to replace all the different ways we're doing this now, and move forward with that?

**Comment by gustaff-weldon** [comment]
@scalvert if you can automate `setupSinonTest(hooks);` by setting those up on `test-helper` or another-level, so it does not have to be called in every test file, that's a bonus. 
Atm, even `setupSinonTest(hooks);` in ember-sinon-qunit would be a step forward IMHO.

**Comment by scalvert** [comment]
@gustaff-weldon you can absolutely do that. The intent of the hooks APIs was to encourage compsability. So, you would likely create local versions of `setupTest`, `setupRenderingTest`, and `setupApplicationTest` within a common location inside your app, and add the hooks calls there. That seems fine.

@elwayman02 the thing I prefer about how ember-sinon-sandbox works is that it doesn't require importing a different test implementation. It just hooks into `testStart` and `testDone`, and everything else is the same.

I did some work this weekend on ember-sinon-sandbox, mainly stripping out some of its features as I found they were unnecessary. I've also migrated the code to a new repo that's been renamed to `ember-sinon-sinoff` (you can blame @rwjblue's wife for that name), as part of the reworking I'm doing is to take advantage of `sinon` 5's automatic sandboxing of the `sinon` object. As such, we won't even use sandboxes to manage the resetting, but simply reset `sinon` after each test.

What do you think about deprecating both `ember-sinon-qunit` and `ember-sinon-sandbox` in favor of `ember-sinon-sinoff`?

**Comment by sukima** [comment]
I'm a little confused. sinon already has its own sandbox and integrates with qunit easily. I've done the following with both old and **new** style tests with no problems (going on 2+ years now).

1.  Install addon

2.  Add the following to `tests/test-helper.js`:

```js
import 'ember-sinon-qunit/test-support/test';
```
3.  Use sinon's asserts:

```js
test('it works', async function() {
  this.actionSpy = sinon.stub().returns(true);
  await render(hbs`<MyCompunent id="test" @action={{this.actionSpy}}/>`);
  await click('#test');
  sinon.assert.calledWith(this.actionSpy, sinon.match.string);
});
```

**Comment by sukima** [comment]
On the topic of sandboxing. I am also confused as the need. The only time a sandbox is needed is for clean up and the only time you have clean up is if you stub a global object that leaks from test to test.

In Ember 99% of the tests are likely already self contained. By the time the test is done any *instances* that were created and stubbed are gone (stubs and all).

In the case of needing to write a global stub a simple

```js
hooks.afterEach(function() {
  sinon.restore();
});
```

is all that is needed and is arguably explicit. In fact if this could simply be part of the QUnit integration or exposed via test-support:

```js
import { setupSinon } from 'ember-sinon-qunit/test-support/setup-sinon';

module('foo', function(hooks) {
  setupRenderingTest(hooks);
  setupSinon(hooks);
});
```

Maybe I'm missing the need for yet **more** addons for something that is not *really* necessary?

**Comment by elwayman02** [comment]
Recapping offline discussion:

- We'll be deprecating both `ember-sinon-sandbox` and [`ember-sinon-sinoff`](https://github.com/scalvert/ember-sinon-sinoff) in favor of `ember-sinon-qunit`
- The current implementation in `ember-sinon-qunit` will be deprecated in favor of the implementation in `ember-sinon-sinoff`. The old pattern will be supported in the interim until a future major release removes it.
- We'll provide a migration guide for all 3 addons so that their users can easily switch over.

Checklist:

- [ ] Migrate functionality from `sinoff`
- [ ] Document new functionality
- [ ] Add deprecation warnings for old functionality
- [ ] Migration guide for `ember-sinon-qunit`
- [ ] Migration guide for `ember-sinon-sandbox`
- [ ] Migration guide for `ember-sinon-sinoff`
- [ ] Release new major version of `ember-sinon-qunit`
- [ ] Mark `ember-sinon-sandbox` as deprecated
- [ ] Mark `ember-sinon-sinoff` as deprecated

**Comment by scalvert** [comment]
Thanks for putting this together, @elwayman02!
