### ISSUE TITLE
Expose fake the same way other APIs are used

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-sinon-qunit#186]
See: https://medium.com/@mudflye/using-fakes-from-ember-sinon-qunit-c9fb7d4d9b1d

**Comment by derekwsgray** [comment]
https://github.com/elwayman02/ember-sinon-qunit/pull/187

**Comment by derekwsgray** [comment]
The PR was merged - I think this can be closed now. Thanks!
