### ISSUE TITLE
ember-sinon dep and peer dep

### ISSUE THREAD

**Issue by kellyselden** [elwayman02/ember-sinon-qunit#194]
`ember-sinon` is a dependency of this project. It is also added to the host app in the blueprint install `addAddonToProject('ember-sinon')`. This is unnecessary and could cause confusion when the versions get out of sync.

**Comment by elwayman02** [comment]
Hmm, this is a fair point. It seems like we could leave `ember-sinon` as a dependency and remove it from the blueprint, since developers could still pin it to a different version if needed.

**Comment by elwayman02** [comment]
Apparently, I legitimately did this once already and then reverted it. Current me hates past me.

https://github.com/elwayman02/ember-sinon-qunit/commit/b877cb5034c709d5a64ff0a5684c0e32a23d6ca2#diff-872ec4b7d482dfcfecfc9c78d1e89fcc

**Comment by kellyselden** [comment]
Any decision on which to choose?

**Comment by elwayman02** [comment]
Sorry, was away all weekend and haven't looked at this since. I think the answer is definitely to just kill the blueprint here.

**Comment by elwayman02** [comment]
Sorry for the delay on this @kellyselden! This will go out with the next major release.
