### ISSUE TITLE
unable to stub/spy a method decorated with @action

### ISSUE THREAD

**Issue by bgantzler** [elwayman02/ember-sinon-qunit#240]
I am getting the following when attempting to use sinon to spy on a method 
`Attempted to wrap undefined property jsonSettingToSetting as function`
 It turns out the culprit is the method is decorated with @action. How do you use sinon with actions? The action is on a service btw.

**Comment by elwayman02** [comment]
Hmm, my guess is that this has less to do with actions and more to do with how the action decorator works. We currently do nothing special in this regard, but if it doesn't work out of the box we'll have to dig into how to wire everything up for that use-case. Thanks for reporting!

**Comment by bgantzler** [comment]
Yes, it is definitely the decorator. I stepped into the sinon code and it saw an object not a function. My best guess is that @action is defining a property that is returning the wrapped function bound to this. Im figuring sinon would not be able to stub/spy a getter/setter of a property either. But if action is indeed turning the function into a property, sinon is going to have to figure how to spy on ……

Wait. I just remember reading in the sinon docs...…

`stub.get(getterFn) - Replaces a new getter for this stub.`

While it might no be obvious but you might have to do that for @action. Will let you know once I get a chance to try it.

**Comment by cah-briangantzler** [comment]
Ok so yea, here is how you stub an action
`let stubSetting = sinon.stub(service, "jsonSettingToSetting").get(function() {
      return null;
    });`

here is how you spy an action
`let spySetting = sinon.spy(service, "jsonSettingToSetting", ["get"])`

here is how you have to assert
`assert.ok(spySetting.get.calledOnce);`

Not immediately obvious but it pretty much proves `@action` turns a method into a property with only a getter (thats because `let spySetting = sinon.spy(service, "jsonSettingToSetting", ["get", "set"])' will throw an error)

**Comment by elwayman02** [comment]
I'm glad you were able to figure it out! I'm not certain if there is anything we can/should do to make that easier, other than documenting it. Would you be willing to submit a PR that adds a section under the README about how to work with the action decorator?

**Comment by cah-briangantzler** [comment]
Sure, will see what I can do.

Will try to talk to someone at EmberConf and see if they have any insight on why action creates a property.

**Comment by elwayman02** [comment]
Sounds good! I'll also be at EmberConf speaking about Octane, so I'd be happy to chat if you find me walking around! :)

**Comment by elwayman02** [comment]
Closing now that this is documented. Thanks!
