### ISSUE TITLE
Documentation doesn't cover use in addon

### ISSUE THREAD

**Issue by nickiaconis** [elwayman02/ember-sinon-qunit#4]
Very cool project.

I was trying it out in an addon, and I noticed that the import statement described in the README doesn't work. Instead of

```javascript
import test from 'my-addon/tests/ember-sinon-qunit/test';
```

addons must use

```javascript
import test from 'dummy/tests/ember-sinon-qunit/test';
```

Could you update the README to include this information please?

**Comment by elwayman02** [comment]
@nickiaconis I would love to merge a PR updating the README to this effect. Great suggestion!
