### ISSUE TITLE
How can I access the ember config from inside a test?

### ISSUE THREAD

**Issue by erichonkanen** [elwayman02/ember-sinon-qunit#49]
Hello, not sure if this is specific to using this package or not but Im having trouble accessing my app's config from inside a unit test...
```
import { moduleFor } from 'ember-qunit'
import test from 'client-web/tests/ember-sinon-qunit/test'
import config from 'client-web/config/environment'
import startApp from '../../helpers/start-app'

moduleFor 'service:wamp',
  beforeEach: =>
    App = startApp()
    App.config = config

test 'it gets a new connection when `getConnection` method is called', (assert)->
  service = @subject()
  service.getConnection()
  debugger
  assert.ok service
```
It seems like it is being set inside my `beforeEach` but neither `App` nor the `config` itself are available from inside my test... any ideas on why or how to get it in there?

Thanks

**Comment by elwayman02** [comment]
Not specific to this addon, Unit tests don't spin up the whole app. You need an acceptance test for that. I'd try asking for help on the Ember slack!
