### ISSUE TITLE
sinon not auto restoring in embroider builds between tests

### ISSUE THREAD

**Issue by Techn1x** [elwayman02/ember-sinon-qunit#726]
I noticed in some embroider builds I'm doing, sinon does not seem to automatically restore between tests, when I stub certain values

For example
```js
import config from 'my-application/config/environment'
import sinon from 'sinon'
...
test('it does a thing', async function (assert) {
  sinon.stub(config, 'showThing').value(true)

  await render('<MyComponent />')

  assert.dom('.thing').exists()
})

test('it does something else', async function (assert) {
  // config.showThing is still true from the above test!
  await render('<MyComponent />')
})
```

If I place a `sinon.restore()` at the end of the first test, or place it in an afterEach, both tests will pass (regardless of test order).

My test-helper.js file looks like this

```js
import config from 'my-application/config/environment'
import Application from 'my-application/app'
import { setApplication } from '@ember/test-helpers'
import * as QUnit from 'qunit'
import { setup as setupQunitDom } from 'qunit-dom'
import setupSinon from 'ember-sinon-qunit'
import start from 'ember-exam/test-support/start'

setupQunitDom(QUnit.assert)
setApplication(Application.create(config.APP))
setupSinon()
start({
  setupTestIsolationValidation: true,
})
```

Is this a misconfiguration on my part, or an issue with the addon under embroider?

**Comment by Mifrill** [comment]
@Techn1x 
> Is this a misconfiguration on my part

Try to check `setupSinon` in your `tests/test-helper.js ` file, see:
https://github.com/elwayman02/ember-sinon-qunit#usage
This function is responsible for restore:
https://github.com/elwayman02/ember-sinon-qunit/blob/aa3b0b361152bb29e49fe5ef580ec76bd9cc453b/addon-test-support/index.js#L12-L13

**Comment by elwayman02** [comment]
It's possible there's an issue with embroider, but I'm hopeful that #727 may fix that. Up until now, we were importing sinon with ember-sinon, which predates ember-auto-import. The new change will replace it with a better import method, which hopefully will be embroider compatible.

**Comment by Techn1x** [comment]
Amazing, it looks like that change might have done it. No longer seeing the issue on embroider for ember-sinon-qunit v7 with sinon v15 - no longer need my manual sinon restores for certain stubs

Thanks!
