### ISSUE TITLE
ember-sinon-qunit is incompatible with ember-qunit 8.0.1

### ISSUE THREAD

**Issue by lozjackson** [elwayman02/ember-sinon-qunit#885]
after upgrading ember-qunit to 8.0.1 I get the following error when trying to run the tests for our app

> Uncaught Error: QUnit has already been defined.

I've tried reproducing this in a fresh ember app - ember-qunit 8.0.1 works until I installed ember-sinon-qunit (7.1.4).

**Comment by SergeAstapov** [comment]
@lozjackson @elwayman02 I bet this is caused by #891

**Comment by ndekeister-us** [comment]
We have this when migrating to Ember 5, which install `ember-qunit` v8

Created https://github.com/elwayman02/ember-sinon-qunit/pull/914 which solved the issue on my side, didn't investigated deeper on why we have this error now

**Comment by elwayman02** [comment]
#908 and #905 appear to have fixed the problem, but we'll keep this ticket open until the next release so we can confirm the issue is resolved.

**Comment by Techn1x** [comment]
can't wait!! thanks for the hard work

**Comment by elwayman02** [comment]
Please test 7.4.0 and let me know if the issue is resolved!

**Comment by ndekeister-us** [comment]
7.4.0 fixed the issue on my side, tests are running when we use it with ember-qunit@8

Thanks 🎉

**Comment by elwayman02** [comment]
That's fantastic! Great work, everyone.

**Comment by lozjackson** [comment]
can confirm the issue is fixed for me after upgrading to 7.4.0.

Thanks

**Comment by IgnaceMaes** [comment]
Just in case anyone else stumbled upon this issue from Google search: I was still seeing this issue after upgrading to 7.4.0.

After a long search, it turns out there was one test file located inside of the `app` folder. This caused `qunit` to be imported by `ember-auto-import`. Moving that to the `test` folder fixed the issue.
