### ISSUE TITLE
release-it config not working with workspaces

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-sinon-qunit#912]
@SergeAstapov now that we moved to the workspace format, our release-it config isn't working properly. It only bumped the root package.json and not the sub-packages to the new version, and it didn't run `npm publish` for the package at all. Any idea what needs to be done to keep our release scripts working with this new project layout?

See also: https://github.com/elwayman02/ember-sinon-qunit/commit/ac1f6b01e7dfd46b038979bac1ec71058ecc2995
https://github.com/elwayman02/ember-sinon-qunit/commit/88b67c28fca2d6fb11def5d3d3712621600b8ac9

**Comment by elwayman02** [comment]
Additionally, the newly-published package lost its README, so we're going to have to fix that as well inside the project:

https://www.npmjs.com/package/ember-sinon-qunit

**Comment by elwayman02** [comment]
Maybe this would help? https://github.com/release-it-plugins/workspaces

**Comment by elwayman02** [comment]
Aha, I should've known rwjblue's setup tool would have been updated to handle this: https://github.com/rwjblue/create-rwjblue-release-it-setup

Note to self for other packages - use this ^

**Comment by SergeAstapov** [comment]
@elwayman02 tbh I would recommend getting off yarn and use pnpm instead where we could use https://pnpm.io/workspaces#workspace-protocol-workspace and never be trolled like that

**Comment by elwayman02** [comment]
@SergeAstapov I'm not against using pnpm, for sure.
